# Global configuration
seed: 0
experiment_dir: "./experiments/clevrer_stg1"
run_name: version_0
num_images: 16
backend_engine:
  _target_: wiskers.common.backends.CheckpointInference
  model_class:
    _target_: hydra.utils.get_class
    path: wiskers.modules.world_model_module.WorldModelModule

# Data module
data_module:
  _target_: wiskers.datasets.clevrer.data_module.ClevrerImage
  data_dir: "./datasets"
  batch_size: 4
  num_workers: 2
  preprocessing:
    _target_: wiskers.datasets.clevrer.data_module.PreprocessingConfig
    chunk_size: 16
    stride: 16
    resize: [160, 240]
    limit: null
  transform:
    _target_: wiskers.datasets.clevrer.data_module.TransformConfig
    image_size: [80, 120]

# Model and output paths
best_model_path:
  _target_: wiskers.cli.utils.get_latest_checkpoint
  experiment_dir: ${experiment_dir}
  run_name: ${run_name}
  ext: ckpt
output_dir: ${experiment_dir}/${run_name}/outputs
